apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-deployment
    tier: backend