apiVersion: v1
kind: Service
metadata:
  labels:
    app: python    
  name: my-loadbalancer
spec:
  ports:
  - nodePort: 30800
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: python
    app-redis: redis

  type: LoadBalancer