apiVersion: v1
kind: Service
metadata:
  name: svc-lb
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: python-deployment
  ports:
  - name: tcp-port
    protocol: TCP
    port: 8080
    targetPort: 8000